name: 'version-builder'
description: 'Build a version string from date- and build-related components'
inputs:
  format:
    description: 'the format to use for the generated version string'
    required: true
    default: '${year}.${month}.${date}'
outputs:
  version:
    description: 'the generated version string (deprecated)'
  result:
    description: 'the generated string'
runs:
  using: 'node20'
  main: 'dist/index.js'
