name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - develop

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      continue-on-error: true
    - uses: ./
      continue-on-error: true
      with:
        format: '${year}.${month}.${date}'
    - uses: ./
      continue-on-error: true
      with:
        format: '${github.branch}+${github.commit.sha}'
    - uses: ./
      continue-on-error: true
      with:
        format: '${year-2000}'
    - uses: ./
      continue-on-error: true
      with:
        format: '${github.commit.shaShort}'
    - uses: ./
      continue-on-error: true
      with:
        format: '${padZero(minutes)}'
    - uses: ./
      continue-on-error: true
      with:
        format: '${padZero(minutes, 5)}'
    - uses: ./
      continue-on-error: true
      with:
        format: '${year-2000}.${month}${padZero(date)}.${hour}${padZero(minutes)}+${github.pr.string || github.branch}.${github.commit.shaShort}'
