name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - uses: ./
      with:
        format: '${year}.${month}.${date}'
    - uses: ./
      with:
        format: '${github.ref}+${github.sha}'
    - uses: ./
      with:
        format: '${year-2000}'
    - uses: ./
      with:
        format: '${github.sha.substr(0,7)}'
    - uses: ./
      with:
        format: '${padZero(minutes)}'
    - uses: ./
      with:
        format: '${padZero(minutes, 5)}'
    - uses: ./
      with:
        format: '${year-2000}.${month}${padZero(date)}.${hour}${padZero(minutes)}+${github.ref}.${github.sha.substr(0, 7)}'
